name: forge_cli
version: 0.1.0-alpha
publish_to: none

description: Command-line tooling for Forge Studio workflows.

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  analyzer: ^6.5.0
  args: ^2.5.0
  path: ^1.9.0
  json_schema: ^5.1.2
  yaml: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.2
