name: forge_cli
version: 0.1.0-alpha
publish_to: none

description: Command-line tooling for Forge Studio workflows.

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  args: ^2.5.0
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
