name: forge_studio
version: 0.1.0-alpha
publish_to: none

description: Flutter Web application providing the Forge visual IDE.

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
