name: Benchmark Regression Gate

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache cargo artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run benchmarks with JSON export
        run: cargo bench -p forge_engine codegen_multi -- --output-format stable

      - name: Compare against baseline
        run: |
          python scripts/compare_benchmarks.py .forge/benchmarks/forge_t4.json target/criterion/benchmarks.json

      - name: Upload new benchmark data on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-regression-data
          path: target/criterion
