name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/forge_engine
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Cargo fmt check
        run: cargo fmt -- --check
      - name: Cargo clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Validate Forge graph schema
        run: |
          python -m pip install --upgrade pip jsonschema
          python -m jsonschema --schema https://json-schema.org/draft/2020-12/schema --instance ../../forge_spec/graph_schema.json
      - name: Cargo test
        run: cargo test --all-features

  dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
      - name: Enable Flutter web
        run: flutter config --enable-web
      - name: Install Melos
        run: dart pub global activate melos
      - name: Melos bootstrap
        run: melos bootstrap
      - name: Dart format check
        run: melos run format
      - name: Dart analyze
        run: melos run analyze

  benchmarks:
    needs: rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Cargo bench
        run: cargo bench
        working-directory: packages/forge_engine
      - name: Export Criterion summary
        run: python3 scripts/export_benchmarks.py .cargo-target/criterion target/criterion_summary.json
      - name: Compare against baseline
        run: |
          python3 scripts/compare_benchmarks.py \
            packages/forge_engine/benches/criterion_baseline.json \
            target/criterion_summary.json \
            --max-regression 0.1 \
            --absolute-slack 1.0
